/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeadLettersRouteImport } from './routes/dead-letters'
import { Route as OovRouteImport } from './routes/oov'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as WordsIndexRouteImport } from './routes/words/index'
import { Route as WordsWordIdRouteImport } from './routes/words/$wordId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadLettersRoute = DeadLettersRouteImport.update({
  id: '/dead-letters',
  path: '/dead-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const OovRoute = OovRouteImport.update({
  id: '/oov',
  path: '/oov',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsIndexRoute = WordsIndexRouteImport.update({
  id: '/words/',
  path: '/words/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsWordIdRoute = WordsWordIdRouteImport.update({
  id: '/words/$wordId',
  path: '/words/$wordId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dead-letters': typeof DeadLettersRoute
  '/oov': typeof OovRoute
  '/plan': typeof PlanRoute
  '/releases': typeof ReleasesRoute
  '/words/$wordId': typeof WordsWordIdRoute
  '/words/': typeof WordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dead-letters': typeof DeadLettersRoute
  '/oov': typeof OovRoute
  '/plan': typeof PlanRoute
  '/releases': typeof ReleasesRoute
  '/words/$wordId': typeof WordsWordIdRoute
  '/words': typeof WordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dead-letters': typeof DeadLettersRoute
  '/oov': typeof OovRoute
  '/plan': typeof PlanRoute
  '/releases': typeof ReleasesRoute
  '/words/$wordId': typeof WordsWordIdRoute
  '/words/': typeof WordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dead-letters'
    | '/oov'
    | '/plan'
    | '/releases'
    | '/words/$wordId'
    | '/words/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dead-letters'
    | '/oov'
    | '/plan'
    | '/releases'
    | '/words/$wordId'
    | '/words'
  id:
    | '__root__'
    | '/'
    | '/dead-letters'
    | '/oov'
    | '/plan'
    | '/releases'
    | '/words/$wordId'
    | '/words/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeadLettersRoute: typeof DeadLettersRoute
  OovRoute: typeof OovRoute
  PlanRoute: typeof PlanRoute
  ReleasesRoute: typeof ReleasesRoute
  WordsWordIdRoute: typeof WordsWordIdRoute
  WordsIndexRoute: typeof WordsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dead-letters': {
      id: '/dead-letters'
      path: '/dead-letters'
      fullPath: '/dead-letters'
      preLoaderRoute: typeof DeadLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oov': {
      id: '/oov'
      path: '/oov'
      fullPath: '/oov'
      preLoaderRoute: typeof OovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words/': {
      id: '/words/'
      path: '/words'
      fullPath: '/words/'
      preLoaderRoute: typeof WordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words/$wordId': {
      id: '/words/$wordId'
      path: '/words/$wordId'
      fullPath: '/words/$wordId'
      preLoaderRoute: typeof WordsWordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeadLettersRoute: DeadLettersRoute,
  OovRoute: OovRoute,
  PlanRoute: PlanRoute,
  ReleasesRoute: ReleasesRoute,
  WordsWordIdRoute: WordsWordIdRoute,
  WordsIndexRoute: WordsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
