package dev.morpho.data.sound

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import android.util.Log

/**
 * The seven UI sound events from docs/contracts/app-design.md.
 * Files live in `assets/sfx/{name}.wav`, generated by `tools/gen_sfx.py`.
 */
enum class SfxEvent(val assetName: String) {
    /** Soft tick, barely-there. */
    TAP("tap"),

    /** Short marimba ding, upward. */
    CORRECT("correct"),

    /** Muted low thud — never harsh. */
    WRONG("wrong"),

    /** Two-note rise on a mode promotion. */
    PROMOTE("promote"),

    /** Three-note fanfare when a group is cleared. */
    GROUP_COMPLETE("group_complete"),

    /** Soft chime at the end of the review queue. */
    REVIEW_DONE("review_done"),

    /** Sparkle when the streak advances. */
    STREAK("streak"),
}

/**
 * UI sound effects on a [SoundPool].
 *
 * Separate from content audio on purpose (docs/contracts/app-design.md, "Sound
 * design"): two channels with independent volumes. SoundPool gives sub-150 ms latency
 * because every clip is decoded and resident before the first tap.
 *
 * While the Media3 player is speaking, SFX duck to [DUCKED_GAIN] so a celebration
 * never talks over a definition.
 */
class SoundManager(
    context: Context,
    private val isContentAudioPlaying: () -> Boolean = { false },
) {

    private val pool: SoundPool = SoundPool.Builder()
        .setMaxStreams(MAX_STREAMS)
        .setAudioAttributes(
            AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_ASSISTANCE_SONIFICATION)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build(),
        )
        .build()

    private val soundIds = HashMap<SfxEvent, Int>()
    private val loaded = HashSet<Int>()

    @Volatile
    var enabled: Boolean = true

    @Volatile
    var volume: Float = DEFAULT_VOLUME
        set(value) {
            field = value.coerceIn(0f, 1f)
        }

    init {
        pool.setOnLoadCompleteListener { _, sampleId, status ->
            if (status == 0) {
                synchronized(loaded) { loaded += sampleId }
            } else {
                Log.w(TAG, "failed to load sfx sample $sampleId (status $status)")
            }
        }
    }

    /** Decodes every cue up front. Call once at startup. */
    fun preload(context: Context) {
        SfxEvent.entries.forEach { event ->
            if (soundIds.containsKey(event)) return@forEach
            runCatching {
                context.assets.openFd("$ASSET_DIR/${event.assetName}.wav").use { fd ->
                    soundIds[event] = pool.load(fd, PRIORITY)
                }
            }.onFailure { Log.w(TAG, "missing sfx asset for ${event.assetName}", it) }
        }
    }

    fun play(event: SfxEvent) {
        if (!enabled || volume <= 0f) return
        val id = soundIds[event] ?: return
        val ready = synchronized(loaded) { id in loaded }
        if (!ready) return

        val gain = volume * if (isContentAudioPlaying()) DUCKED_GAIN else 1f
        pool.play(id, gain, gain, PRIORITY, /* loop = */ 0, /* rate = */ 1f)
    }

    fun release() {
        runCatching { pool.release() }
        soundIds.clear()
        synchronized(loaded) { loaded.clear() }
    }

    companion object {
        private const val TAG = "SoundManager"
        private const val ASSET_DIR = "sfx"
        private const val MAX_STREAMS = 4
        private const val PRIORITY = 1
        const val DEFAULT_VOLUME = 0.8f

        /** Contract: duck SFX to 0.6 while content audio is playing. */
        const val DUCKED_GAIN = 0.6f
    }
}
